backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "photos"
public_folder: "/photos"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "index.html"
        label: "Main Page"
        name: "main_page"
        fields:
          - { label: "Logo Image", name: "logo", widget: "image" }
          - { label: "Landing Title", name: "landing_heading", widget: "string" }
          - { label: "Landing Divider Image", name: "divider", widget: "image" }
          - { label: "Landing Text", name: "landing_text", widget: "text" }
          - { label: "CTA Heading", name: "cta_heading", widget: "string" }
          - label: "CTA Logos"
            name: "cta_logos"
            widget: "list"
            fields:
              - { label: "Logo Image", name: "img", widget: "image" }
              - { label: "Link", name: "link", widget: "string" }

          - label: "Company Story"
            name: "story"
            widget: "text"

          - { label: "Company Section Image", name: "company_image", widget: "image" }
